### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dorayya62**
Updated readme.md file with a true line

### CODE REVIEW

**Comment by pajayreddy** [comment]
This is not a butterfly this is a mosquito, please change it to mosquito

**Comment by Dorayya62** [comment]
but this is a butterfly, I saw it...

**Comment by pajayreddy** [comment]
But change it to mosquito

**Comment by Dorayya62** [comment]
Changed, Please approve

**Comment by pajayreddy** [comment]
ok

**Pull request merged**
